"""initial from current models

Revision ID: 1a929437f3bf
Revises: 
Create Date: 2026-05-30 12:42:12.652917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a929437f3bf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('department_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('department_id')
    )
    op.create_index(op.f('ix_departments_code'), 'departments', ['code'], unique=True)
    op.create_index(op.f('ix_departments_is_active'), 'departments', ['is_active'], unique=False)
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=False)
    op.create_table('holidays',
    sa.Column('holiday_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('holiday_id')
    )
    op.create_index(op.f('ix_holidays_holiday_date'), 'holidays', ['holiday_date'], unique=True)
    op.create_table('leave_types',
    sa.Column('leave_type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('max_days_per_year', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('leave_type_id')
    )
    op.create_index(op.f('ix_leave_types_code'), 'leave_types', ['code'], unique=True)
    op.create_index(op.f('ix_leave_types_is_active'), 'leave_types', ['is_active'], unique=False)
    op.create_index(op.f('ix_leave_types_is_paid'), 'leave_types', ['is_paid'], unique=False)
    op.create_table('positions',
    sa.Column('position_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('position_id')
    )
    op.create_index(op.f('ix_positions_code'), 'positions', ['code'], unique=True)
    op.create_index(op.f('ix_positions_is_active'), 'positions', ['is_active'], unique=False)
    op.create_index(op.f('ix_positions_name'), 'positions', ['name'], unique=False)
    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Enum('admin', 'hr', 'manager', 'employee', name='role_name'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('work_shifts',
    sa.Column('shift_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_overnight', sa.Boolean(), nullable=False),
    sa.Column('late_threshold_minutes', sa.Integer(), nullable=False),
    sa.Column('early_leave_threshold_minutes', sa.Integer(), nullable=False),
    sa.Column('required_work_minutes', sa.Integer(), nullable=True, comment='Required working minutes to count as full attendance'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('shift_id')
    )
    op.create_index(op.f('ix_work_shifts_code'), 'work_shifts', ['code'], unique=True)
    op.create_index(op.f('ix_work_shifts_is_active'), 'work_shifts', ['is_active'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'locked', name='user_status'), nullable=False),
    sa.Column('token_version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refresh_token_hash', sa.Text(), nullable=True),
    sa.Column('refresh_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refresh_token_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('log_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('performed_by', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('create', 'update', 'delete', 'approve', 'reject', 'login', 'logout', 'revoke', 'manual_edit', name='audit_action'), nullable=False),
    sa.Column('object_type', sa.String(), nullable=False),
    sa.Column('object_id', sa.String(), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['performed_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_object_id'), 'audit_logs', ['object_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_object_type'), 'audit_logs', ['object_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_performed_by'), 'audit_logs', ['performed_by'], unique=False)
    op.create_table('employees',
    sa.Column('employee_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('employee_code', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True, comment='male | female | other'),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('resignation_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'resigned', name='employee_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.employee_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.position_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_index(op.f('ix_employees_department_id'), 'employees', ['department_id'], unique=False)
    op.create_index(op.f('ix_employees_employee_code'), 'employees', ['employee_code'], unique=True)
    op.create_index(op.f('ix_employees_full_name'), 'employees', ['full_name'], unique=False)
    op.create_index(op.f('ix_employees_manager_id'), 'employees', ['manager_id'], unique=False)
    op.create_index(op.f('ix_employees_position_id'), 'employees', ['position_id'], unique=False)
    op.create_index(op.f('ix_employees_status'), 'employees', ['status'], unique=False)
    op.create_index(op.f('ix_employees_user_id'), 'employees', ['user_id'], unique=True)
    op.create_table('notifications',
    sa.Column('notification_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('attendance', 'leave', 'correction', 'system', 'face_registration', name='notification_type'), nullable=False),
    sa.Column('object_type', sa.String(), nullable=True, comment='leave_request | correction_request | attendance_record | face_profile'),
    sa.Column('object_id', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('system_settings',
    sa.Column('setting_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('setting_id')
    )
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    op.create_table('attendance_events',
    sa.Column('event_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Enum('check_in', 'check_out', 'unknown', name='attendance_event_type'), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('anti_spoof_score', sa.Float(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('raw_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Full JSON response từ AI service'),
    sa.Column('is_accepted', sa.Boolean(), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_attendance_events_employee_id'), 'attendance_events', ['employee_id'], unique=False)
    op.create_index(op.f('ix_attendance_events_event_time'), 'attendance_events', ['event_time'], unique=False)
    op.create_index(op.f('ix_attendance_events_event_type'), 'attendance_events', ['event_type'], unique=False)
    op.create_table('attendance_records',
    sa.Column('record_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('work_date', sa.DateTime(), nullable=False),
    sa.Column('check_in_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('present', 'late', 'early_leave', 'late_and_early_leave', 'absent', 'on_leave', 'holiday', 'missing_check_in', 'missing_check_out', 'manually_edited', name='attendance_record_status'), nullable=False),
    sa.Column('late_minutes', sa.Integer(), nullable=False),
    sa.Column('early_leave_minutes', sa.Integer(), nullable=False),
    sa.Column('worked_minutes', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('face_recognition', 'manual', 'edited', 'system', name='attendance_source'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_id'], ['work_shifts.shift_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_index(op.f('ix_attendance_records_employee_id'), 'attendance_records', ['employee_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_shift_id'), 'attendance_records', ['shift_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_source'), 'attendance_records', ['source'], unique=False)
    op.create_index(op.f('ix_attendance_records_status'), 'attendance_records', ['status'], unique=False)
    op.create_index(op.f('ix_attendance_records_work_date'), 'attendance_records', ['work_date'], unique=False)
    op.create_table('department_managers',
    sa.Column('manager_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('manager_id', 'department_id')
    )
    op.create_index(op.f('ix_department_managers_department_id'), 'department_managers', ['department_id'], unique=False)
    op.create_table('employee_shift_assignments',
    sa.Column('assignment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_id'], ['work_shifts.shift_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_index(op.f('ix_employee_shift_assignments_effective_date'), 'employee_shift_assignments', ['effective_date'], unique=False)
    op.create_index(op.f('ix_employee_shift_assignments_employee_id'), 'employee_shift_assignments', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_shift_assignments_end_date'), 'employee_shift_assignments', ['end_date'], unique=False)
    op.create_index(op.f('ix_employee_shift_assignments_shift_id'), 'employee_shift_assignments', ['shift_id'], unique=False)
    op.create_table('face_profiles',
    sa.Column('profile_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'revoked', 'failed', name='face_profile_status'), nullable=False),
    sa.Column('qdrant_collection', sa.String(), nullable=False, comment='Tên collection trong Qdrant'),
    sa.Column('qdrant_point_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='List vector IDs, e.g. ["uuid-1", "uuid-2", ...]'),
    sa.Column('embedding_model', sa.String(), nullable=True, comment='e.g. buffalo_l / arcface'),
    sa.Column('embedding_version', sa.String(), nullable=True, comment='Dùng khi switch sang model mới'),
    sa.Column('registered_by', sa.UUID(), nullable=True),
    sa.Column('revocation_reason', sa.Text(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registered_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_index(op.f('ix_face_profiles_employee_id'), 'face_profiles', ['employee_id'], unique=True)
    op.create_index(op.f('ix_face_profiles_qdrant_collection'), 'face_profiles', ['qdrant_collection'], unique=False)
    op.create_index(op.f('ix_face_profiles_status'), 'face_profiles', ['status'], unique=False)
    op.create_table('leave_requests',
    sa.Column('request_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('leave_type_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('time_type', sa.Enum('full_day', 'morning', 'afternoon', 'custom', name='leave_time_type'), nullable=False),
    sa.Column('total_days', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'cancelled', name='leave_request_status'), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['employees.employee_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.leave_type_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_index(op.f('ix_leave_requests_employee_id'), 'leave_requests', ['employee_id'], unique=False)
    op.create_index(op.f('ix_leave_requests_end_date'), 'leave_requests', ['end_date'], unique=False)
    op.create_index(op.f('ix_leave_requests_leave_type_id'), 'leave_requests', ['leave_type_id'], unique=False)
    op.create_index(op.f('ix_leave_requests_start_date'), 'leave_requests', ['start_date'], unique=False)
    op.create_index(op.f('ix_leave_requests_status'), 'leave_requests', ['status'], unique=False)
    op.create_table('attendance_correction_requests',
    sa.Column('request_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('attendance_record_id', sa.UUID(), nullable=True),
    sa.Column('requested_check_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_check_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'cancelled', name='correction_request_status'), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attendance_record_id'], ['attendance_records.record_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['employees.employee_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_index(op.f('ix_attendance_correction_requests_attendance_record_id'), 'attendance_correction_requests', ['attendance_record_id'], unique=False)
    op.create_index(op.f('ix_attendance_correction_requests_employee_id'), 'attendance_correction_requests', ['employee_id'], unique=False)
    op.create_index(op.f('ix_attendance_correction_requests_reviewed_by'), 'attendance_correction_requests', ['reviewed_by'], unique=False)
    op.create_index(op.f('ix_attendance_correction_requests_status'), 'attendance_correction_requests', ['status'], unique=False)
    op.create_table('leave_approval_logs',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('leave_request_id', sa.UUID(), nullable=False),
    sa.Column('approver_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('approved', 'rejected', 'forwarded', 'cancelled', name='approval_action'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['employees.employee_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['leave_request_id'], ['leave_requests.request_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_leave_approval_logs_action'), 'leave_approval_logs', ['action'], unique=False)
    op.create_index(op.f('ix_leave_approval_logs_approver_id'), 'leave_approval_logs', ['approver_id'], unique=False)
    op.create_index(op.f('ix_leave_approval_logs_created_at'), 'leave_approval_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_leave_approval_logs_leave_request_id'), 'leave_approval_logs', ['leave_request_id'], unique=False)
    op.create_table('attendance_correction_logs',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('correction_request_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('approved', 'rejected', 'forwarded', 'cancelled', name='approval_action'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('old_check_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('old_check_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('new_check_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('new_check_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['correction_request_id'], ['attendance_correction_requests.request_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['employees.employee_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_attendance_correction_logs_action'), 'attendance_correction_logs', ['action'], unique=False)
    op.create_index(op.f('ix_attendance_correction_logs_correction_request_id'), 'attendance_correction_logs', ['correction_request_id'], unique=False)
    op.create_index(op.f('ix_attendance_correction_logs_created_at'), 'attendance_correction_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_attendance_correction_logs_reviewer_id'), 'attendance_correction_logs', ['reviewer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_correction_logs_reviewer_id'), table_name='attendance_correction_logs')
    op.drop_index(op.f('ix_attendance_correction_logs_created_at'), table_name='attendance_correction_logs')
    op.drop_index(op.f('ix_attendance_correction_logs_correction_request_id'), table_name='attendance_correction_logs')
    op.drop_index(op.f('ix_attendance_correction_logs_action'), table_name='attendance_correction_logs')
    op.drop_table('attendance_correction_logs')
    op.drop_index(op.f('ix_leave_approval_logs_leave_request_id'), table_name='leave_approval_logs')
    op.drop_index(op.f('ix_leave_approval_logs_created_at'), table_name='leave_approval_logs')
    op.drop_index(op.f('ix_leave_approval_logs_approver_id'), table_name='leave_approval_logs')
    op.drop_index(op.f('ix_leave_approval_logs_action'), table_name='leave_approval_logs')
    op.drop_table('leave_approval_logs')
    op.drop_index(op.f('ix_attendance_correction_requests_status'), table_name='attendance_correction_requests')
    op.drop_index(op.f('ix_attendance_correction_requests_reviewed_by'), table_name='attendance_correction_requests')
    op.drop_index(op.f('ix_attendance_correction_requests_employee_id'), table_name='attendance_correction_requests')
    op.drop_index(op.f('ix_attendance_correction_requests_attendance_record_id'), table_name='attendance_correction_requests')
    op.drop_table('attendance_correction_requests')
    op.drop_index(op.f('ix_leave_requests_status'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_start_date'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_leave_type_id'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_end_date'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_employee_id'), table_name='leave_requests')
    op.drop_table('leave_requests')
    op.drop_index(op.f('ix_face_profiles_status'), table_name='face_profiles')
    op.drop_index(op.f('ix_face_profiles_qdrant_collection'), table_name='face_profiles')
    op.drop_index(op.f('ix_face_profiles_employee_id'), table_name='face_profiles')
    op.drop_table('face_profiles')
    op.drop_index(op.f('ix_employee_shift_assignments_shift_id'), table_name='employee_shift_assignments')
    op.drop_index(op.f('ix_employee_shift_assignments_end_date'), table_name='employee_shift_assignments')
    op.drop_index(op.f('ix_employee_shift_assignments_employee_id'), table_name='employee_shift_assignments')
    op.drop_index(op.f('ix_employee_shift_assignments_effective_date'), table_name='employee_shift_assignments')
    op.drop_table('employee_shift_assignments')
    op.drop_index(op.f('ix_department_managers_department_id'), table_name='department_managers')
    op.drop_table('department_managers')
    op.drop_index(op.f('ix_attendance_records_work_date'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_status'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_source'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_shift_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_employee_id'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index(op.f('ix_attendance_events_event_type'), table_name='attendance_events')
    op.drop_index(op.f('ix_attendance_events_event_time'), table_name='attendance_events')
    op.drop_index(op.f('ix_attendance_events_employee_id'), table_name='attendance_events')
    op.drop_table('attendance_events')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_employees_user_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_status'), table_name='employees')
    op.drop_index(op.f('ix_employees_position_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_manager_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_full_name'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_code'), table_name='employees')
    op.drop_index(op.f('ix_employees_department_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_audit_logs_performed_by'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_object_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_object_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_work_shifts_is_active'), table_name='work_shifts')
    op.drop_index(op.f('ix_work_shifts_code'), table_name='work_shifts')
    op.drop_table('work_shifts')
    op.drop_table('roles')
    op.drop_index(op.f('ix_positions_name'), table_name='positions')
    op.drop_index(op.f('ix_positions_is_active'), table_name='positions')
    op.drop_index(op.f('ix_positions_code'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_leave_types_is_paid'), table_name='leave_types')
    op.drop_index(op.f('ix_leave_types_is_active'), table_name='leave_types')
    op.drop_index(op.f('ix_leave_types_code'), table_name='leave_types')
    op.drop_table('leave_types')
    op.drop_index(op.f('ix_holidays_holiday_date'), table_name='holidays')
    op.drop_table('holidays')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_index(op.f('ix_departments_is_active'), table_name='departments')
    op.drop_index(op.f('ix_departments_code'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
